In [1]:
cd /Volumes/GoogleDrive/My Drive/Classes/Harvard_Classes/_Current/CS207/cs107-FinalProject/socialAD

/Volumes/GoogleDrive/My Drive/Classes/Harvard_Classes/_Current/CS207/cs107-FinalProject/socialAD


In [2]:
from forward import *

In [3]:
import numpy as np
from scipy.optimize import minimize
import matplotlib.pyplot as plt
from matplotlib import cm, ticker

from scipy.optimize import line_search


In [21]:
import time

41469.235458223
41469.245498636


In [22]:
np.array([dfx1(x0), dfx2(x0)])

array([13,  6])

In [5]:
#
def obj_func(param):
    x, y = param
    return 100 *(y - (x)**2)**2 +(1 - x)**2
def obj_grad(param):
    x, y = param
    return np.array([2 *(-1 + x + 200 *x**3 - 200* x *y), 200* (-x**2 + y)] )
# analytical solution 




In [6]:
def visual(x1, x2, y1, y2, POINTS, F):    
    all_x = np.linspace(x1, x2, 100)
    all_y = np.linspace(y1, y2, 100)
    all_z = F(np.meshgrid(all_x, all_y))
    p_array = np.array(POINTS)
    x = p_array[:, 0]
    y = p_array[:, 1] 
    plt.contourf(all_x, all_y, all_z, cmap\
                 = cm.copper, locator=ticker.LogLocator())
    plt.plot(x, y, marker='x', color = 'white')
    plt.colorbar()
    plt.xlim((x1, x2))
    plt.ylim((y1, y2))
    plt.show()

In [23]:
a = np.array([3]) # Value of x to be evaluated 
x = forwardAD(a, numvar = 2, idx = 0)

b = np.array([2]) # Value of y to be evaluated 
y = forwardAD(b, numvar = 2, idx = 1)

f1 = x*y
f2 = x**2 + y**2

sys = vector_func(f1, f2)
print(sys.jacobian())
print(sys.values())
print(f1.der)

[[2. 3.]
 [6. 4.]]
[[ 6]
 [13]]
[2. 3.]


In [39]:
#  Backtracking line search algorithm


import numpy as np
alpha = 0.3
beta = 0.8

f = lambda x: (x[0]**2 + 3*x[1]*x[0] + 12)

# TRADITIONALLY 
dfx1 = lambda x: (2*x[0] + 3*x[1])
dfx2 = lambda x: (3*x[0])



t = 1
count = 1
x0 = np.array([2,3])  # initial guess 
dx0 = np.array([.1, 0.05])


def backtrack(x0, dfx1, dfx2, t, alpha, beta, count):
    t_start = time.monotonic()


    while (f(x0) - (f(x0 - t*np.array([dfx1(x0), dfx2(x0)])) + alpha * t * np.dot(np.array([dfx1(x0), dfx2(x0)]), np.array([dfx1(x0), dfx2(x0)])))) < 0:
        t *= beta
#         print("""
# ###  iteration {}   ###
# """.format(count))
#         print("Inequality: ",  f(x0) - (f(x0 - t*np.array([dfx1(x0), dfx2(x0)])) + alpha * t * np.dot(np.array([dfx1(x0), dfx2(x0)]), np.array([dfx1(x0), dfx2(x0)]))))
        count += 1
    t_stop = time.monotonic()
    print( f'Time elapsed: {t_stop - t_start} seconds ')
    return t

t = backtrack(x0, dfx1, dfx2, t, alpha, beta, count)

# find the distance "t" 

print("\nFinal step size :",  t)


Time elapsed: 0.00039381799433613196 seconds 

Final step size : 0.32768000000000014


In [37]:
# Try to optimize... does not really work 
# t = 1
# count = 1
# x0 = np.array([2,3])
# dx0 = np.array([.1, 0.05])


# def backtrack(x0, dfx1, dfx2, t, alpha, beta, count):
#     t_start = time.monotonic()

#     fx0 = f(x0)
#     grad = np.array([dfx1(x0), dfx2(x0)])
#     while (fx0 - (f(x0 - t*grad) + alpha * t * np.dot(grad, grad))) < 0:
#         t *= beta
#         count += 1
#     t_stop = time.monotonic()
#     print( f'Time elapsed: {t_stop - t_start} seconds ')
#     return t

# t = backtrack(x0, dfx1, dfx2, t, alpha, beta, count)

# # find the distance "t" 

# print("\nfinal step size :",  t)


In [38]:

###############
# USING OUR PACAKGE 

a = np.array([2])
x = forwardAD(a, numvar = 2, idx = 0)

b = np.array([3]) 
y = forwardAD(b, numvar = 2, idx = 1)

f_AD =(x)**2 + 3*y*x + 12


t = 1
count = 1
x0 = np.array([2,3]) # initial guess 
# dx0 = np.array([.1, 0.05])



def backtrack_AD(x0, t, alpha, beta, count):
    t_start = time.monotonic()
    x = forwardAD(x0[0], numvar = 2, idx = 0)
    y = forwardAD(x0[1], numvar = 2, idx = 1)
    f_AD =(x)**2 + 3*y*x + 12
    
    while (f_AD.val - (f(x0 - t*f_AD.der) + alpha * t * np.dot( f_AD.der, f_AD.der))) < 0:
        t *= beta
        count += 1
    t_stop = time.monotonic()
    print( f'Time elapsed: {t_stop - t_start} seconds ')    
    return t

t = backtrack_AD(x0, t, alpha, beta, count)



# find the distance "t" 

print("\nFinal step size :",  t)

Time elapsed: 0.00010402500629425049 seconds 

Final step size : 0.32768000000000014


In [ ]:
# vs  0.001603826996870339 seconds 

In [ ]:
# A SIMPLE WAY OF PERFORMING STEEPEST GRADIENT 





t = 1
count = 1

def backtrack_AD(x0, t, alpha, beta, count):
    t_start = time.monotonic()
    x = forwardAD(x0[0], numvar = 2, idx = 0)
    y = forwardAD(x0[1], numvar = 2, idx = 1)
    f_AD =(x)**2 + 3*y*x + 12
    
    while (f_AD.val - (f(x0 - t*f_AD.der) + alpha * t * np.dot( f_AD.der, f_AD.der))) < 0:
        t *= beta
        count += 1
    t_stop = time.monotonic()
    #print( f'Time elapsed: {t_stop - t_start} seconds ')    
    return t

t = backtrack_AD(x0, t, alpha, beta, count)


iter_n = 0
max_iter = 2000
delta_points = 1
p = 1e-8


################################################
t_start_opt = time.monotonic()

points = np.array([2, 3]) # x0

# grad = - obj_grad(points)

all_points = []
all_points.append(points)


x = forwardAD(points[0], numvar = 2, idx = 0)
y = forwardAD(points[1], numvar = 2, idx = 1)
f_AD =(x)**2 + 3*y*x + 12

grad = - f_AD.der    
while delta_points > p and iter_n < max_iter:
#     alpha, fc, gc, new_fval, old_fval, new_slope = line_search(obj_func, obj_grad, points, grad) 
    t = backtrack_AD(points, 1, alpha, beta, 1)
    new_points = points + grad*t 
    delta_points = np.sqrt((new_points[0] - points[0])**2 + (new_points[1] - points[1])**2)
    iter_n += 1
    

    points = new_points
    x = forwardAD(points[0], numvar = 2, idx = 0)
    y = forwardAD(points[1], numvar = 2, idx = 1)
    f_AD =(x)**2 + 3*y*x + 12
    
    grad = -f_AD.der
    all_points.append(points)
    print(f"Iteration #{iter_n}, {points}")
t_stop_opt = time.monotonic()

print(f'OPTIMIZATION elapsed time: {t_stop_opt - t_start_opt} seconds ')  
print(f"After {iter_n} iterations, the minimum point is estimated to be at {points}")

### (a) Minimize Rosenbrock’s function using steepest descent.

In [42]:
# traditional way of doing this 
points = np.array([2,3]) 
grad = -obj_grad(points)
iter_n = 0
max_iter = 2000
delta_points = 1
p = 1e-8
all_points = []
all_points.append(points)
while delta_points > p and iter_n < max_iter:
    alpha, fc, gc, new_fval, old_fval, new_slope = line_search(obj_func, obj_grad, points, grad) 
#    if np.mod(iter_n, 250) == 0:
#         print(points)
#         print(delta_points)
    new_points = points + grad*alpha 
    delta_points = np.sqrt((new_points[0] - points[0])**2 + (new_points[1] - points[1])**2)
    grad = -new_slope
    iter_n += 1
    points = new_points
    all_points.append(points)

print(f"After {iter_n} iterations, the minimum point is estimated to be at {points}")

NameError: name 'obj_grad' is not defined