<p class="title"> CS107 Final Project</p>

<p class="subtitle">Group 29</p>

<center>

<p class="gap05"<p>
<h2>SocialAD Package</h2>

<p class="gap05"<p>
<h3> Ju Chulakadabba, Dashiell Young-Saver, Tao Tsui, Jenny Wang
</h3>
<h3>Harvard University</h3>

<p class="gap2"<p>
</center>

## Section I: Introduction to socialAD

Our software provides users with functions that find roots and stationary points of equations. 
The algorithms implemented are powered by automatic differentiation (forward mode). 


Automatic differentiation allows our alogrithms to solve derivatives quickly and to machine precision, 
which means our root and stationary finding algorithms are more efficient than many packages built on finite difference methods.

## Background

- Finding Roots
    - **Newton's Method**
    - **Broyden's Method**

- Finding Minima
    - **Gradient Descent**
    - **Broyden–Fletcher–Goldfarb–Shanno (BFGS)**

All of these methods require finding derivatives, a Jacobian, or a Jacobian approximation!    

## Automatic Differentiation 

- Used to power our package, automatic differentiation (forward mode) uses the chain rule to step through complex functions and calculate derivatives.
- Users can use the forward mode of our automatic differentiation methods for their own purposes (outside of our root-finding algorithms), if desired
- Our package also computes second-order derivatives, for use in finding local minima and maxima

## A Deriviate We May Have to Evaluate

$~$


$$f(x,y)=\begin{bmatrix} x^2+y^2 \\ \exp(x+y) \end{bmatrix}.$$

$$J=\begin{bmatrix} \partial f_{1} / \partial x & \partial f_{1} / \partial y \\ \partial f_{2} / \partial x & \partial f_{2} / \partial y \end{bmatrix}=\begin{bmatrix} 2x & 2y \\ \exp(x+y) & \exp(x+y) \end{bmatrix}$$

$~$

Evaluate it at the point (1,1):

$$J=\begin{bmatrix} 2 & 2 \\ 7.38906 & 7.38906 \end{bmatrix}$$

## How can we do this to machine precision?

Get the simpler derivatives on each *level* of the function, and then carry those derivatives through the whole function throught the chain rule!

## Using The Chain Rule for Automatic Differentiation

The chain rule is used to evaluate the derivative of a function by differentiating the outer function, multiplied by the derivative of the inner function, until all layers of the function are complete.

Suppose we have a function $F(x) = f(g(x))$, then $F'(x) = f'(g(x))g'(x)$.

We can traverse a function $f(x)$ by following what happens to its input, $x$. We evaluate from the innermost layer and work our way outwards. For each layer, we calculate its derivative and then feed that as the input to the next layer.

## What it looks like: Trace Tables

| trace   | elem op.      | value    | elem derivative          | $\nabla_{x}$| $\nabla_{y}$ |
| :---:   | :------:      | :---:    | :---------------------:  | :---------: | :----------: |
| $x_{1}$ | $x_{1}$       | $1$      | $\dot{x}_{1}$            |    $1$      |    $0$       |
| $x_{2}$ | $x_{2}$       | $1$     | $\dot{x}_{2}$            | $0$         | $1$         |
| $v_{1}$ | $x_{1}^{2}$   | $1$      | $2x_{1}\dot{x}_{1}$      | $2$         | $0$          |
| $v_{2}$ | $x_{2}^{2}$   | $1$      | $2x_2\dot{x}_{2}$| $0$   | $2$        |
| $v_{3}$ | $v_{1}+v_{2}$ | $2$      | $\dot{v}_1+\dot{v}_2$    | $2$         | $2$      |

## Positive Broader Impacts

There are multiple ways to use our package for greater scientific and social good. 
There are also ways to misuse our package in these respects.

The functions we provide are widely applicable in many fields. 
- Engineers use root-finding to optimize space given material constraints. 
- Data scientists use root-finding to inform machine learning models. 
- Physicists find stationary points to map particle motion.
- Economists find stationary points to describe changing markets.

To the extent that fields may use our package to spur innovation, solve problems that help humanity, 
create a more efficient workforce and economy, and work towards a more advanced and just world - we will 
be proud our package made some contribution to these efforts.

## Potential Negative Broader Impact

However, alongside innovation can come consequences. 

For example, 
our gradient descement implementations may be used in machine learning implementations, which sometimes have been used in negative contexts:
- Introducing bias in 
[policing and in court systems](https://www.propublica.org/article/machine-bias-risk-assessments-in-criminal-sentencing)
- Taking [jobs away](https://time.com/5876604/machines-jobs-coronavirus/) from the service industry
  (and others)
- Accelerated new ways of [illegal hacking](https://techhq.com/2020/09/how-hackers-are-weaponizing-artificial-intelligence/). 

In addition, fields of science that could utilize our package and that spur technological innovation (such as physics) 
  can also spur great human loss with that innovation (such as the invention of the atomic bomb - as one historic example). 
  We strongly encourage those who use our package to consider the consequences of their work, especially as they apply their 
  work to contexts that are prone to the types of issues mentioned above. 

## Software Inclusivity

Our package is open-source on GitHub, and pull requests can be made by anyone who has a free GitHub account. 
The package authors (Tao, Jenny, Ju, and Dash) will approve pull requests after collectively discussing the impact of
 those pull requests. We will review pull requests without viewing the personal details of user accounts who make them, 
 thus preventing some level of bias in our decisions.

## Section II: Implementation

### Installation

Our package is on _pip_. You can open up a terminal and run the following in your work environment:

`$ pip install socialAD`

To upgrade the package on your local machine, please run:

`$ pip install socialAD --upgrade`

### Software Organization

General structure of our package:

![software_orgo](./img/software_orgo.jpg)

`/socialAD` contains scripts for all of our base classes and extensions:
* `forward.py`: basic implementation of forward mode
* `root_finding.py`: Broyden function
* `gradient.py`: gradient descent
* `forward_pro.py`: second derivatives

`/tests` contains all of our tests
* `/runtests.py` executes the tests

`/docs` contains documentation

#### For developers

First, clone the repository to your local machine:

`$ git clone https://github.com/climate-change-is-real-python-dev/cs107-FinalProject.git`


Go to the repository:

`$ cd /path/to/cs107-FinalProject`


##### Installing dependencies

`$ pip install -r requirements.txt`


##### Running unit tests

Say you have written an optimization function and would like to test it. You can create a unit test file called `optimization_tests.py` in the `tests` folder:

`$ cd /path/to/cs107-FinalProject/tests`


`$ touch optimization_tests.py`

After creating test cases, head over to the top level and open `runtests.py`:

`$ cd ..`


`$ vi runtests.py`

Add the following line to `runtests.py`:

`$ runpy.run_path(path_name='tests/optimization_tests.py')`

Stay in `cs107-FinalProject` and run:

`$ chmod +x runtests.py`


`$ ./runtests.py`

Or this:

`$ python runtests.py`


### Implementation Details

`forwardAD` class:
* Attributes: `.val` and `.der`
* Arithmetic operators
* Comparison operators
* Elementary functions
* Vector functions

### How to Use

#### Scalar inputs

Instantiate a `forwardAD` object:

In [1]:
from socialAD.forward import forwardAD
x = forwardAD(3)

Write a function of `x` of your choice:

In [2]:
f = (x + 5)**2

Evaluate `f` and find its derivative at `x = 3`:

In [3]:
print("Function value: {}".format(f.val))
print("Derivative value: {}".format(f.der))

Function value: 64
Derivative value: [16.]


![simple_val](./img/2_simple_val.jpg)
![simple_der](./img/3_simple_der.jpg)

You can also try a more complex function:

In [4]:
from socialAD.forward import e
import numpy as np

# Instantiate initial input to function
x = forwardAD(5)

# Function (note: make multiplication explicit)
f = e()**x - (2 - 6 * x - 3 * x ** 5)

# Get function value at x = 5 and derivative at x = 5
print("Function value: {}".format(f.val))
print("Derivative value: {}".format(f.der))

Function value: 9551.413159102576
Derivative value: [9529.4131591]


![complex_val](./img/4_complex_val.jpg)
![complex_der](./img/5_complex_der.jpg)

#### Vector inputs

Workflow to compute the values and the Jacobian:

In [5]:
from socialAD.forward import vector_func

a = np.array([3])
x = forwardAD(a, numvar = 2, idx = 0)

b = np.array([2])
y = forwardAD(b, numvar = 2, idx = 1)

f1 = x*y
f2 = x**2 + y**2

v = vector_func(f1, f2)
values_v = v.values
jacobian_v = v.jacobian

print("Function values: \n{}".format(values_v()))
print("Jacobian: \n{}".format(jacobian_v()))

Function values: 
[[ 6]
 [13]]
Jacobian: 
[[2. 3.]
 [6. 4.]]


#### Simple root-finding use case

In [6]:
# Initialize root value and step value
root = 0.0
dx = 50

# While step is greater than a very small number
while dx > 1e-20:

    # Instantiate a forward AD object at root guess
    x = forwardAD(root)

    # Write our function
    f = e()**x - (2 - 6*x - 3 * x ** 5)

    # Get step using Newton's Method
    dx = -f.val / f.der

    # Save new root with new step
    root = root + dx
    
print("Root value: {}".format(root))
print("Function value at root: {}".format(f.val))

Root value: [0.14133666]
Function value at root: [0.01088635]


![complex_root1](./img/6_complex_root1.jpg)
![complex_root1](./img/6_complex_root2.jpg)

#### Comparison operators

In [7]:
x = forwardAD(4)
y = forwardAD(7)
f1 = 4*x + 3*y
f2 = 3*x + 4*y

print("Value of f1: {}".format(f1.val))
print("Value of f2: {}".format(f2.val))
print("Derivative of f1: {}".format(f1.der))
print("Derivative of f2: {}".format(f2.der))

print("\n")

# For equality and inequality, true only if both val and der are true
print("Equality: {}".format(f1 == f2)) # Expected: val false, der true, therefore false
print("Inequality: {}".format(f1 != f2)) # Expected: val true, der false, therefore false
print("Less than: {}".format(f1 < f2)) # Expected: val true, der false, therefore false
print("Less than or equal to: {}".format(f1 <= f2)) # Expected: val true, der true, therefore true
print("Greater than: {}".format(f1 > f2)) # Expected: val false, der false, therefore false
print("Greater than or equal to: {}".format(f1 >= f2)) # Expected: val false, der true, therefore false

Value of f1: 37
Value of f2: 40
Derivative of f1: [7.]
Derivative of f2: [7.]


Equality: False
Inequality: False
Less than: [False]
Less than or equal to: [ True]
Greater than: False
Greater than or equal to: False


## Section III: Extensions

### 2nd-order Derivatives


In [8]:
from socialAD.forward_pro import *

#from forward_pro import *

x = forwardAD_pro(0.387)
f = log(1/(arctan(x)*x**2))

print("Function Value: ", f.func.val)
print("1st Derivative: ", f.dera.val)
print("2nd Derivative: ", f.dera.der)

Function Value:  2.8949439051408983
1st Derivative:  -7.523384839521769
2nd Derivative:  [20.48755358]


![complex_root1](./img/2nd_der_1.png)


In [9]:
x = forwardAD_pro(0.387)
f = e()**x*log(x**3/(cosh(x)*x**2))

print("Function Value: ", f.func.val)
print("1st Derivative: ", f.dera.val)
print("2nd Derivative: ", f.dera.der)

Function Value:  -1.5055671924729173
1st Derivative:  1.7564520982201164
2nd Derivative:  [-6.08601388]


![complex_root1](./img/2nd_der_2.png)

### Root-finding Algorithms

#### Newton's Method



- Approximates roots by setting an initial guess, then iteratively subtracting the function value scaled by the derivative from the latest guess. This eventually provides very precise (if not exact) approximations of roots.
- For scalar non-vector functions: $x_{n+1}=x_{n}-{\frac {f(x_{n})}{f'(x_{n})}}$
- For vector functions: $x_{n+1}=x_{n}-J_{F}(x_{n})^{-1}F(x_{n})$


In [10]:
from socialAD.root_finding import newton

import numpy as np

### Tests of Newton ###

print('Case: vector function, single variable')
print('Should get root of 5')
functions = ["x**2 - 25", "x - 5"]
print(newton(functions,"x",[50]))
print('\n')

print('Case: vector function, multple variables')
print('Should get roots of 1 and 1')
functions = ["x + y - 2", "x - y"]
print(newton(functions,["x","y"],[4,4]))
print('\n')

Case: vector function, single variable
Should get root of 5
(array([5.]), array([[6.17159657e-10],
       [6.17159657e-11]]))


Case: vector function, multple variables
Should get roots of 1 and 1
(array([1., 1.]), array([[1.33226763e-15],
       [1.33226763e-15]]))




#### Broyden's Method

- This method is extremely similar to Newton's method, except that it employs finite differences after the first step of the Newton iteration. So, for a non-vector function, it computes finite differences at each iteration after the first. For vector functions, it computes a finitely-updated Jacobian at each iteration after the first.
- Mostly used in applications in which the Jacobian is computationally expensive to calculate. This method saves the machine from having to calculate a new Jacobian at each step.


In [11]:
from socialAD.root_finding import broyden
import numpy as np 

### Tests of broyden ###

print('Case: non-vector function, multiple variables')
print('Should get roots of 2.53 and -14.29')
print(broyden("y + x**3 + 3*x**2 - 21",["x","y"],[3, 7]))
print('\n')

print('Case: vector function, single variable')
print('Should get root of 5')
functions = ["x**2 - 25", "x - 5"]
print(broyden(functions,"x",[50]))
print('\n')

print('Case: vector function, multple variables')
print('Should get roots of 1 and 1')
functions = ["x + y - 2", "x - y"]
print(broyden(functions,["x","y"],[4,4]))
print('\n')

Case: non-vector function, multiple variables
Should get roots of 2.53 and -14.29
(array([  2.52688749, -14.29006302]), array([-7.98751429e-08]))


Case: vector function, single variable
Should get root of 5
(array([5.00000001]), array([[9.10860187e-08],
       [9.10860187e-09]]))


Case: vector function, multple variables
Should get roots of 1 and 1
(array([1., 1.]), array([[1.33226763e-15],
       [1.33226763e-15]]))




### Gradient Descent & BFGS
#### One variable 

- **Gradient Descent**
    - Common in the world of machine learning, gradient descent steps through the steepest gradient drop direction until the method finds a stationary point.
    - Our implementation allows the user to change the steps size and to use backtrack line search.
- **BFGS**
    - BFGS is an iterative method for solving unconstrained nonlinear optimization problems. Instead of directly solving for the Hessian matrix, we just approximate it.  We basically follow the descent direction by preconditioning the gradient with curvature information.  

In [12]:
import socialAD.forward as fw
import socialAD.gradient as gd
import numpy as np
import time

def generate_timer(function):
    def with_timer():
        t_start = time.monotonic()
        function
        t_stop = time.monotonic()
        print( f'Time elapsed: {t_stop - t_start} seconds ')
        print('--------------------------------------------')
    return with_timer

In [13]:
variables = ["x"]
f = "(x+5)**2 "
cur_x = [3]
rate = 0.1
precision = 0.000001
previous_step_size = 1
max_iters = 10000
iters = 0

In [14]:

print('============================================')
print('GRADIENT DESCENT')
print('============================================')

a = generate_timer(gd.gradient_descent(variables, f, cur_x, rate, precision, previous_step_size, max_iters))
a()

print('============================================')
print('GD WITH BACKTRACK LINE SEARCH')
print('============================================')

a = generate_timer(gd.gd_backtrack(variables, f, cur_x, precision, previous_step_size, max_iters))
a()

GRADIENT DESCENT
Iteration 66
The local minimum occurs at [-4.99999679]
Time elapsed: 2.720000000788758e-07 seconds 
--------------------------------------------
GD WITH BACKTRACK LINE SEARCH
Iteration 14
The local minimum occurs at [-4.99999985]
Time elapsed: 1.750000000466656e-07 seconds 
--------------------------------------------


In [15]:

print('============================================')
print('BFGS')
print('============================================')
a = generate_timer(gd.BFGS(variables, f, cur_x, precision, max_iters))
a()
print('============================================')
print('BFGS WITH BACKTRACK LINE SEARCH')
print('============================================')
a = generate_timer(gd.BFGS_backtrack(variables, f, cur_x, precision, max_iters))
a()

BFGS
Iteration 66
The local minimum occurs at [-4.99999679]
Time elapsed: 1.9200000000996198e-07 seconds 
--------------------------------------------
BFGS WITH BACKTRACK LINE SEARCH
Iteration 14
The local minimum occurs at [-4.99999985]
Time elapsed: 2.109999999166945e-07 seconds 
--------------------------------------------


### Gradient Descent & BFGS
#### Multivariable mode

In [16]:

variables = ["x","y"]
f = "(x+5)**2 + y**2"
cur_x = [3, 1]

print('============================================')
print('GRADIENT DESCENT')
print('============================================')

a = generate_timer(gd.gradient_descent(variables, f, cur_x, rate, precision, previous_step_size, max_iters))
a()

print('============================================')
print('GD WITH BACKTRACK LINE SEARCH')
print('============================================')

a = generate_timer(gd.gd_backtrack(variables, f, cur_x, precision, previous_step_size, max_iters))
a()

print('============================================')
print('BFGS')
print('============================================')
a  = generate_timer(gd.BFGS(variables, f, cur_x, precision, max_iters))
a()
print('============================================')
print('BFGS WITH BACKTRACK LINE SEARCH')
print('============================================')
a = generate_timer(gd.BFGS_backtrack(variables, f, cur_x, precision, max_iters))
a()

GRADIENT DESCENT
Iteration 66
The local minimum occurs at [-4.99999679e+00  4.01734511e-07]
Time elapsed: 3.1899999997087036e-07 seconds 
--------------------------------------------
GD WITH BACKTRACK LINE SEARCH
Iteration 14
The local minimum occurs at [-4.99999985e+00  1.82059120e-08]
Time elapsed: 1.0830000000128237e-06 seconds 
--------------------------------------------
BFGS
Iteration 66
The local minimum occurs at [-4.99999684e+00  3.94944181e-07]
Time elapsed: 1.5500000005719272e-07 seconds 
--------------------------------------------
BFGS WITH BACKTRACK LINE SEARCH
Iteration 14
The local minimum occurs at [-4.99999985e+00  1.83903042e-08]
Time elapsed: 1.7400000007494754e-07 seconds 
--------------------------------------------


## Section IV: Conclusion & Future work

What we have delivered so far... 

* Auto-diff from scratch with various optimization & root finding algorithms 

Advantages of our package

* Rigorous, user-friendly, and customizable 

 ![rxn_rate](img/summary_figure.jpeg)

### Real world aplications 
* Economics 
    * Various econometric applications 
    * For example: a Fisher Market problem (spending constraint utilities)
 ![rxn_rate](img/fisher_1.png)
    



        



* Environemental Engineering
    * Inverse modeling: estimating emissions based on measured concentrations and prior information

 ![rxn_rate](img/inverse.jpeg) 

* Chemistry
    * Estimate reaction rates 
 ![rxn_rate](img/rxn_rate.png)

### Hopefully, you are interested in our package by now. Feel free to download our package using

`$ pip install socialAD`