In [25]:
cd /Volumes/GoogleDrive/My Drive/Classes/Harvard_Classes/_Current/CS207/cs107-FinalProject/socialAD

/Volumes/GoogleDrive/My Drive/Classes/Harvard_Classes/_Current/CS207/cs107-FinalProject/socialAD


In [26]:
from forward import *

### Partial derivative of equations when inputs are vectors 

In [27]:
a = np.array([3]) # Value of x to be evaluated 
x = forwardAD(a)
x_const = a # will use this in the partial derivative wrt z example below

b = np.array([2]) # Value of y to be evaluated 
y = forwardAD(b)
y_const = b # will use this in the partial derivative wrt z example below

c = np.array([1, 3, 5]) # Vector of z values to be evaluated 
z = forwardAD(c)


$i(x,y,z) = xy + z$

$i'(x,y,z) = y + x + 1 = 2 + 3 + 1 = 6$ regardless of z values

$j(x, y, z) = x^2 + 2xz$

$j'(x, y, z) = 2x + 2z + 2x = 12 + 2z = [14, 18, 22]$

= [dj/dx, dj/dy, dj/dz] = [2x + 2z, 0, 2z]


$k = xz$

$k'(x, y, z) = x + z = z + 3 = [4, 6, 8]$


In [28]:
i = x*y+z 
j = x**2 + 2*x*z
k = x*z
print(i.val, j.val, k.val)
print(i.der, j.der, k.der)

# AS WE EXPECTED 

[ 7  9 11] [15 27 39] [ 3  9 15]
[6. 6. 6.] [14. 18. 22.] [4. 6. 8.]


In [31]:
d = np.array([2, 5, 5]) # Value of w to be evaluated 
w = forwardAD(d)
w_const = d

In [34]:
# Perform a partial derivative of  j wrt z
# Need to treat the other terms to be constant
f_partial_z = x_const**2 + 2*w_const*z**2 + 3*y_const

# with another vector input (w_const)
print(f_partial_z[0].val)
print(f_partial_z[0].der)

print('====================')
f_partial_z = x_const**2 + 2*x_const*z**2 + 3*y_const

# z is the only vector input
print(f_partial_z[0].val)
print(f_partial_z[0].der)



[ 19  51 115]
[ 8. 24. 40.]
[ 21  69 165]
[12. 36. 60.]
